### ISSUE TITLE
dbpath requirement

### ISSUE THREAD

**Issue by nullvariable** [crowdsecurity/cs-custom-blocker#7]
I wasn't able to get this working until I had both the 
```
db_config:
  db_path: ...
```
and
```
dbpath: ...
```
defined in my cs-custom-blocker.yaml file.

I'm guessing there was a refactor somewhere along the way, it works fine as long as I define both those paths.

**Comment by buixor** [comment]
oh indeed ... thanks for spotting it, new release on its way !

**Comment by buixor** [comment]
release v0.0.4 should fix the bug @nullvariable , thanks !

**Comment by nullvariable** [comment]
confirmed working, thanks!
